CircleCI copied from aas repo

diff --git a/.circleci/generate-circleci-config b/.circleci/generate-circleci-config
--- a/.circleci/generate-circleci-config
+++ b/.circleci/generate-circleci-config
@@ -2,9 +2,24 @@
 
 set -euo pipefail
 
+if [ "$(uname)" = "Darwin" ]; then
+	if brew ls --versions coreutils > /dev/null; then
+		# The package is installed
+		SCRIPT=$(greadlink -f -- $0)
+		CPCMD="gcp -f"
+	else
+		# The package is not installed
+		echo 'no coreutils found. install it with `brew install coreutils`'
+		exit 1
+	fi
+else
+	# assume linux, windows will never be true computing
+	SCRIPT=$(readlink -f -- $0)
+	CPCMD="cp -f"
+fi
+
 CIRCLECI_FILE=config.yml
 LOCAL_FILE=local_config.yml
-SCRIPT=$(readlink -f -- $0)
 SCRIPTPATH=$(dirname $SCRIPT)
 SCRIPTNAME=$(basename $SCRIPT)
 DIR=$(mktemp -d)
@@ -21,6 +36,31 @@ else
 	git clone -q git@github.com:dbmedialab/ci $DIR/ci
 fi
 
+CONFIG_VERSION="2"
+PARAMS=""
+while (( "$#" )); do
+  case "$1" in
+    -c|--config-version)
+      CONFIG_VERSION=$2
+      shift 2
+      ;;
+    --) # end argument parsing
+      shift
+      break
+      ;;
+    -*|--*=) # unsupported flags
+      echo "Error: Unsupported flag $1" >&2
+      exit 1
+      ;;
+    *) # preserve positional arguments
+      PARAMS="$PARAMS $1"
+      shift
+      ;;
+  esac
+done
+# set positional arguments in their proper place
+eval set -- "$PARAMS"
+
 cd $SCRIPTPATH
 
 cat << EOF > $CIRCLECI_FILE
@@ -35,7 +75,7 @@ cat << EOF > $CIRCLECI_FILE
 # https://github.com/dbmedialab/ci/blob/master/common_aliases.yml
 #
 
-version: 2
+version: $CONFIG_VERSION
 
 EOF
 
@@ -50,8 +90,6 @@ cat << EOF >> $CIRCLECI_FILE
 #
 #########################################################################
 
-version: 2
-
 EOF
 
 # local config
@@ -62,7 +100,7 @@ echo "* generated config.yml from local and remote config"
 # compare md5sums of running and upstream scripts, replace if diff
 if [[ "$(cat $SCRIPT | md5sum)" != "$(cat $DIR/ci/$SCRIPTNAME | md5sum)" ]]; then
 	echo "* updating local $0"
-	cp --force $DIR/ci/$SCRIPTNAME $SCRIPT
+	$CPCMD $DIR/ci/$SCRIPTNAME $SCRIPT
 fi
 
 cd - > /dev/null
